import { Student } from './types';

export const TEACHER_CREDENTIALS = {
  username: 'major',
  password: '123456',
};

// Fix: Explicitly type as number to avoid comparison errors in other files.
// TypeScript was inferring the literal types 16 and 10, which can never be 0.
export const TOTAL_MEETINGS: number = 16;
export const TOTAL_TASKS: number = 10;

export const INITIAL_STUDENTS_DATA: Student[] = [
  {
    id: 1,
    name: 'Budi Santoso',
    nim: '12345',
    picture: 'https://picsum.photos/seed/budi-santoso/200',
    attendance: { hadir: 14, izin: 1, sakit: 1 },
    exams: { mid1: 85, final1: 90, mid2: 88, final2: 92 },
    proactiveness: { bertanya: 10, menjawab: 5, menambahkan: 3 },
    tasks: { selesai: 9 },
  },
  {
    id: 2,
    name: 'Citra Lestari',
    nim: '67890',
    picture: 'https://picsum.photos/seed/citra-lestari/200',
    attendance: { hadir: 16, izin: 0, sakit: 0 },
    exams: { mid1: 92, final1: 95, mid2: 90, final2: 98 },
    proactiveness: { bertanya: 15, menjawab: 10, menambahkan: 5 },
    tasks: { selesai: 10 },
  },
  {
    id: 3,
    name: 'Dewi Anggraini',
    nim: '54321',
    picture: 'https://picsum.photos/seed/dewi-anggraini/200',
    attendance: { hadir: 12, izin: 2, sakit: 2 },
    exams: { mid1: 78, final1: 80, mid2: 82, final2: 85 },
    proactiveness: { bertanya: 5, menjawab: 3, menambahkan: 1 },
    tasks: { selesai: 8 },
  },
  {
    id: 4,
    name: 'Eko Prasetyo',
    nim: '23456',
    picture: 'https://picsum.photos/seed/eko-prasetyo/200',
    attendance: { hadir: 15, izin: 1, sakit: 0 },
    exams: { mid1: 80, final1: 85, mid2: 82, final2: 88 },
    proactiveness: { bertanya: 8, menjawab: 4, menambahkan: 2 },
    tasks: { selesai: 9 },
  },
  {
    id: 5,
    name: 'Fajar Nugroho',
    nim: '34567',
    picture: 'https://picsum.photos/seed/fajar-nugroho/200',
    attendance: { hadir: 13, izin: 2, sakit: 1 },
    exams: { mid1: 75, final1: 78, mid2: 80, final2: 82 },
    proactiveness: { bertanya: 6, menjawab: 2, menambahkan: 1 },
    tasks: { selesai: 7 },
  },
  {
    id: 6,
    name: 'Gita Permata',
    nim: '45678',
    picture: 'https://picsum.photos/seed/gita-permata/200',
    attendance: { hadir: 16, izin: 0, sakit: 0 },
    exams: { mid1: 95, final1: 98, mid2: 94, final2: 97 },
    proactiveness: { bertanya: 12, menjawab: 8, menambahkan: 4 },
    tasks: { selesai: 10 },
  },
  {
    id: 7,
    name: 'Hadi Wibowo',
    nim: '56789',
    picture: 'https://picsum.photos/seed/hadi-wibowo/200',
    attendance: { hadir: 14, izin: 0, sakit: 2 },
    exams: { mid1: 88, final1: 90, mid2: 85, final2: 89 },
    proactiveness: { bertanya: 7, menjawab: 5, menambahkan: 3 },
    tasks: { selesai: 9 },
  },
  {
    id: 8,
    name: 'Indah Sari',
    nim: '67891',
    picture: 'https://picsum.photos/seed/indah-sari/200',
    attendance: { hadir: 15, izin: 1, sakit: 0 },
    exams: { mid1: 90, final1: 92, mid2: 91, final2: 94 },
    proactiveness: { bertanya: 9, menjawab: 6, menambahkan: 4 },
    tasks: { selesai: 10 },
  },
  {
    id: 9,
    name: 'Joko Susilo',
    nim: '78912',
    picture: 'https://picsum.photos/seed/joko-susilo/200',
    attendance: { hadir: 11, izin: 3, sakit: 2 },
    exams: { mid1: 70, final1: 75, mid2: 72, final2: 78 },
    proactiveness: { bertanya: 4, menjawab: 2, menambahkan: 0 },
    tasks: { selesai: 6 },
  },
  {
    id: 10,
    name: 'Kartika Putri',
    nim: '89123',
    picture: 'https://picsum.photos/seed/kartika-putri/200',
    attendance: { hadir: 16, izin: 0, sakit: 0 },
    exams: { mid1: 91, final1: 94, mid2: 92, final2: 96 },
    proactiveness: { bertanya: 14, menjawab: 9, menambahkan: 6 },
    tasks: { selesai: 10 },
  },
  {
    id: 11,
    name: 'Lutfi Hakim',
    nim: '91234',
    picture: 'https://picsum.photos/seed/lutfi-hakim/200',
    attendance: { hadir: 13, izin: 1, sakit: 2 },
    exams: { mid1: 82, final1: 85, mid2: 80, final2: 84 },
    proactiveness: { bertanya: 5, menjawab: 3, menambahkan: 2 },
    tasks: { selesai: 8 },
  },
  {
    id: 12,
    name: 'Maya Indriani',
    nim: '11234',
    picture: 'https://picsum.photos/seed/maya-indriani/200',
    attendance: { hadir: 15, izin: 0, sakit: 1 },
    exams: { mid1: 89, final1: 91, mid2: 88, final2: 93 },
    proactiveness: { bertanya: 11, menjawab: 7, menambahkan: 3 },
    tasks: { selesai: 9 },
  },
  {
    id: 13,
    name: 'Nana Supriatna',
    nim: '12234',
    picture: 'https://picsum.photos/seed/nana-supriatna/200',
    attendance: { hadir: 12, izin: 2, sakit: 2 },
    exams: { mid1: 78, final1: 80, mid2: 79, final2: 81 },
    proactiveness: { bertanya: 6, menjawab: 4, menambahkan: 1 },
    tasks: { selesai: 7 },
  },
  {
    id: 14,
    name: 'Oki Setiawan',
    nim: '12334',
    picture: 'https://picsum.photos/seed/oki-setiawan/200',
    attendance: { hadir: 14, izin: 1, sakit: 1 },
    exams: { mid1: 85, final1: 88, mid2: 86, final2: 90 },
    proactiveness: { bertanya: 8, menjawab: 5, menambahkan: 2 },
    tasks: { selesai: 9 },
  },
  {
    id: 15,
    name: 'Putri Ayu',
    nim: '12344',
    picture: 'https://picsum.photos/seed/putri-ayu/200',
    attendance: { hadir: 16, izin: 0, sakit: 0 },
    exams: { mid1: 94, final1: 96, mid2: 93, final2: 98 },
    proactiveness: { bertanya: 13, menjawab: 10, menambahkan: 5 },
    tasks: { selesai: 10 },
  },
  {
    id: 16,
    name: 'Rizky Amelia',
    nim: '12346',
    picture: 'https://picsum.photos/seed/rizky-amelia/200',
    attendance: { hadir: 15, izin: 1, sakit: 0 },
    exams: { mid1: 90, final1: 93, mid2: 89, final2: 95 },
    proactiveness: { bertanya: 10, menjawab: 7, menambahkan: 4 },
    tasks: { selesai: 10 },
  },
  {
    id: 17,
    name: 'Surya Wijaya',
    nim: '12347',
    picture: 'https://picsum.photos/seed/surya-wijaya/200',
    attendance: { hadir: 13, izin: 2, sakit: 1 },
    exams: { mid1: 81, final1: 84, mid2: 83, final2: 86 },
    proactiveness: { bertanya: 7, menjawab: 4, menambahkan: 2 },
    tasks: { selesai: 8 },
  },
  {
    id: 18,
    name: 'Tika Wulandari',
    nim: '12348',
    picture: 'https://picsum.photos/seed/tika-wulandari/200',
    attendance: { hadir: 14, izin: 0, sakit: 2 },
    exams: { mid1: 87, final1: 89, mid2: 88, final2: 91 },
    proactiveness: { bertanya: 9, menjawab: 6, menambahkan: 3 },
    tasks: { selesai: 9 },
  },
  {
    id: 19,
    name: 'Umar Faruq',
    nim: '12349',
    picture: 'https://picsum.photos/seed/umar-faruq/200',
    attendance: { hadir: 12, izin: 3, sakit: 1 },
    exams: { mid1: 76, final1: 79, mid2: 77, final2: 80 },
    proactiveness: { bertanya: 5, menjawab: 2, menambahkan: 1 },
    tasks: { selesai: 7 },
  },
  {
    id: 20,
    name: 'Vina Candrawati',
    nim: '12350',
    picture: 'https://picsum.photos/seed/vina-candrawati/200',
    attendance: { hadir: 15, izin: 1, sakit: 0 },
    exams: { mid1: 92, final1: 95, mid2: 90, final2: 97 },
    proactiveness: { bertanya: 11, menjawab: 8, menambahkan: 5 },
    tasks: { selesai: 10 },
  },
  {
    id: 21,
    name: 'Wahyu Hidayat',
    nim: '12351',
    picture: 'https://picsum.photos/seed/wahyu-hidayat/200',
    attendance: { hadir: 14, izin: 1, sakit: 1 },
    exams: { mid1: 84, final1: 87, mid2: 85, final2: 88 },
    proactiveness: { bertanya: 8, menjawab: 6, menambahkan: 2 },
    tasks: { selesai: 9 },
  },
  {
    id: 22,
    name: 'Yulia Puspita',
    nim: '12352',
    picture: 'https://picsum.photos/seed/yulia-puspita/200',
    attendance: { hadir: 16, izin: 0, sakit: 0 },
    exams: { mid1: 93, final1: 97, mid2: 94, final2: 99 },
    proactiveness: { bertanya: 12, menjawab: 9, menambahkan: 6 },
    tasks: { selesai: 10 },
  },
  {
    id: 23,
    name: 'Zainal Abidin',
    nim: '12353',
    picture: 'https://picsum.photos/seed/zainal-abidin/200',
    attendance: { hadir: 11, izin: 2, sakit: 3 },
    exams: { mid1: 72, final1: 76, mid2: 74, final2: 78 },
    proactiveness: { bertanya: 4, menjawab: 1, menambahkan: 0 },
    tasks: { selesai: 6 },
  },
  {
    id: 24,
    name: 'Aditya Pratama',
    nim: '12354',
    picture: 'https://picsum.photos/seed/aditya-pratama/200',
    attendance: { hadir: 15, izin: 0, sakit: 1 },
    exams: { mid1: 88, final1: 91, mid2: 89, final2: 92 },
    proactiveness: { bertanya: 9, menjawab: 7, menambahkan: 3 },
    tasks: { selesai: 9 },
  },
  {
    id: 25,
    name: 'Bella Saphira',
    nim: '12355',
    picture: 'https://picsum.photos/seed/bella-saphira/200',
    attendance: { hadir: 14, izin: 2, sakit: 0 },
    exams: { mid1: 86, final1: 89, mid2: 87, final2: 90 },
    proactiveness: { bertanya: 10, menjawab: 6, menambahkan: 4 },
    tasks: { selesai: 9 },
  },
  {
    id: 26,
    name: 'Candra Gunawan',
    nim: '12356',
    picture: 'https://picsum.photos/seed/candra-gunawan/200',
    attendance: { hadir: 13, izin: 1, sakit: 2 },
    exams: { mid1: 79, final1: 82, mid2: 80, final2: 83 },
    proactiveness: { bertanya: 6, menjawab: 3, menambahkan: 1 },
    tasks: { selesai: 8 },
  },
  {
    id: 27,
    name: 'Dinda Kirana',
    nim: '12357',
    picture: 'https://picsum.photos/seed/dinda-kirana/200',
    attendance: { hadir: 16, izin: 0, sakit: 0 },
    exams: { mid1: 96, final1: 99, mid2: 95, final2: 100 },
    proactiveness: { bertanya: 15, menjawab: 11, menambahkan: 7 },
    tasks: { selesai: 10 },
  },
  {
    id: 28,
    name: 'Farhan Jauhari',
    nim: '12358',
    picture: 'https://picsum.photos/seed/farhan-jauhari/200',
    attendance: { hadir: 12, izin: 2, sakit: 2 },
    exams: { mid1: 77, final1: 81, mid2: 78, final2: 83 },
    proactiveness: { bertanya: 5, menjawab: 3, menambahkan: 2 },
    tasks: { selesai: 7 },
  },
  {
    id: 29,
    name: 'Gisela Anastasia',
    nim: '12359',
    picture: 'https://picsum.photos/seed/gisela-anastasia/200',
    attendance: { hadir: 15, izin: 1, sakit: 0 },
    exams: { mid1: 91, final1: 94, mid2: 90, final2: 96 },
    proactiveness: { bertanya: 11, menjawab: 8, menambahkan: 4 },
    tasks: { selesai: 10 },
  },
  {
    id: 30,
    name: 'Heru Santoso',
    nim: '12360',
    picture: 'https://picsum.photos/seed/heru-santoso/200',
    attendance: { hadir: 14, izin: 1, sakit: 1 },
    exams: { mid1: 83, final1: 86, mid2: 84, final2: 87 },
    proactiveness: { bertanya: 7, menjawab: 5, menambahkan: 2 },
    tasks: { selesai: 8 },
  },
  {
    id: 31,
    name: 'Intan Permatasari',
    nim: '12361',
    picture: 'https://picsum.photos/seed/intan-permatasari/200',
    attendance: { hadir: 16, izin: 0, sakit: 0 },
    exams: { mid1: 92, final1: 96, mid2: 93, final2: 98 },
    proactiveness: { bertanya: 13, menjawab: 9, menambahkan: 5 },
    tasks: { selesai: 10 },
  },
  {
    id: 32,
    name: 'Kevin Sanjaya',
    nim: '12362',
    picture: 'https://picsum.photos/seed/kevin-sanjaya/200',
    attendance: { hadir: 13, izin: 0, sakit: 3 },
    exams: { mid1: 80, final1: 84, mid2: 82, final2: 85 },
    proactiveness: { bertanya: 9, menjawab: 4, menambahkan: 1 },
    tasks: { selesai: 9 },
  },
  {
    id: 33,
    name: 'Lina Marlina',
    nim: '12363',
    picture: 'https://picsum.photos/seed/lina-marlina/200',
    attendance: { hadir: 15, izin: 1, sakit: 0 },
    exams: { mid1: 89, final1: 92, mid2: 90, final2: 94 },
    proactiveness: { bertanya: 10, menjawab: 7, menambahkan: 4 },
    tasks: { selesai: 9 },
  },
  {
    id: 34,
    name: 'Miko Wijaya',
    nim: '12364',
    picture: 'https://picsum.photos/seed/miko-wijaya/200',
    attendance: { hadir: 12, izin: 2, sakit: 2 },
    exams: { mid1: 75, final1: 78, mid2: 76, final2: 80 },
    proactiveness: { bertanya: 5, menjawab: 2, menambahkan: 0 },
    tasks: { selesai: 6 },
  },
  {
    id: 35,
    name: 'Nadia Putri',
    nim: '12365',
    picture: 'https://picsum.photos/seed/nadia-putri/200',
    attendance: { hadir: 14, izin: 1, sakit: 1 },
    exams: { mid1: 85, final1: 88, mid2: 86, final2: 90 },
    proactiveness: { bertanya: 8, menjawab: 5, menambahkan: 3 },
    tasks: { selesai: 9 },
  },
];
